In [3]:
import pandas as pd
import numpy as np
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
import sklearn as skl

#  **Second Run**

In [4]:
kaggle_train_aac = pd.read_csv('kaggle_train.csv')

In [5]:
kaggle_train_aac

Labels     ACAN      AGER      ALPK1    ANKRD17     APOB      APPL1  \
0         0  13.6584   88.0205   402.5420  1424.2625   3.7940  1001.2330   
1         0  22.0844   86.3807   690.4861  2226.3285  20.4071   486.9744   
2         0  32.7422   53.0820   128.4882  1073.0497   0.0000   654.8431   
3         0  22.7975   42.1175   634.0804  3285.5487   0.0000   574.9614   
4         0   2.5000  134.0625   532.1875   936.5625   0.0000  1933.4375   
..      ...      ...       ...        ...        ...      ...        ...   
247       1  61.3497  209.2706   300.6135   676.8916   4.0900   866.3940   
248       1  25.0447   89.7436  1050.3876  1677.6983   0.0000  1019.0817   
249       0  18.8321   50.5493   631.0399  1997.8525   0.3304   821.6734   
250       0  17.2414   92.8100   825.3852  2262.6559   0.3668  1421.8635   
251       0  30.6291   96.0265   541.6667  2443.4327   0.2759  2218.5403   

         APPL2      ARRB2    ASGR1  ...      UBE2N     UBE2V1     UBQLN1  \
0     508.0148   567.2010  13.6584  ...  2437.6363  3413.2107  4135.4453   
1    1448.0640   651.9083  11.1820  ...  2153.9253  1817.3762  3426.4325   
2     492.6206   512.9604  13.8906  ...  3122.4110  3720.6995  3000.3721   
3     513.9104  1033.2303  31.6847  ...  2663.4467  3217.9212  4131.3756   
4     679.3750  1175.6250   6.5625  ...  1898.4375  3009.1375  2549.3750   
..         ...        ...      ...  ...        ...        ...        ...   
247   836.4008   903.8855  40.8998  ...  2700.7498  2858.8957  1663.9400   
248  2058.1395  2086.4639   3.8760  ...  1367.0244  2176.7352  2595.4085   
249   941.9344   912.1996  17.8409  ...  2085.7355  2405.6562  3461.1382   
250   960.7483  1231.1079   2.9347  ...  2774.0279  2888.9142  4561.6288   
251  1235.9272   961.6446   4.4150  ...  2553.8079  2839.9558  4388.2450   

          UFD1    UNC93B1  USP17L2       VCAN      WDFY1       XIAP    ZCCHC3  
0     950.0104  1434.1269   0.0000    31.8695   923.0769  1046.0021  819.1217  
1    1380.1196   815.7241   0.0000  1651.0166  1473.7825  1618.8684  615.8465  
2    2681.3791  1429.2447   0.4961   693.5384   477.2417  1064.6161  804.1672  
3    1178.8640  1018.5471   0.0000   675.0386  1596.5997  1666.1515  402.6275  
4    1293.1156   744.6875   0.0000    69.0625  1651.5625  1250.3125  982.5000  
..         ...        ...      ...        ...        ...        ...       ...  
247  2168.3640  1858.2140   0.0000   441.0361   586.9121   583.5037  732.1063  
248  1222.4120  2648.4794   0.0000   471.9738  1548.5987  1888.4914  788.6106  
249  1596.0981   665.7306   0.3304  1272.3218   763.8556  1522.4250  347.2371  
250  1594.2296   653.7051   0.0000   392.5165  2422.9640  1749.0829  768.1585  
251  1104.2908   602.6490   0.0000   411.4238   835.5408  1103.2009  713.3002  

[252 rows x 319 columns]

In [7]:
Y=kaggle_train_aac.Labels

In [10]:
X = kaggle_train_aac.drop(columns=['Labels'])

In [11]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X, Y)

RandomForestClassifier(max_depth=2, random_state=0)

In [13]:
kaggle_test_aac = pd.read_csv('kaggle_test.csv')
testing_data = kaggle_test_aac.drop(columns=['ID'])

In [15]:
test_Y = clf.predict_proba(testing_data)[:,1]

In [28]:
test_Y
aa=(test_Y>0.5).astype(int)

In [29]:
aa

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [31]:
to_upload = pd.DataFrame(aa)
cc = [1000+i+1 for i in range(105)]
dd = pd.concat([pd.DataFrame(cc),pd.DataFrame(to_upload)],axis=1)
dd.columns = ['ID','Labels']
dd.to_csv("second_run.csv", index=False)

In [16]:
df_test = kaggle_test_aac[['ID']]

In [18]:
df_test['Labels'] = test_Y

/var/folders/px/t3y_9w795y96ggv476lfg7dh0000gn/T/ipykernel_16103/495855424.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['Labels'] = test_Y


In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_valid.shape

NameError: name 'X_valid' is not defined

In [34]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X, Y, test_size=0.2, random_state=42)

In [35]:
y_valid

165    0
6      0
111    0
172    0
115    1
183    1
199    1
235    0
9      1
30     1
60     1
218    0
226    1
159    0
68     0
148    1
196    1
15     1
101    1
24     0
86     0
19     1
117    1
124    0
33     1
242    1
186    0
219    0
10     0
162    1
140    1
96     0
125    0
82     1
213    1
25     0
109    1
18     1
205    1
182    0
67     0
132    1
156    0
143    0
45     1
178    1
16     1
66     1
142    0
175    1
38     0
Name: Labels, dtype: int64

In [36]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [37]:
X_train.shape , y_train.shape

((201, 318), (201,))

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
skl.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [40]:
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X_train, y_train, cv=3, scoring='roc_auc')
scores

array([0.51247772, 0.59536542, 0.73262032])

In [41]:
np.mean(scores)

0.6134878193701724

In [42]:
X_train.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)

In [43]:
from  sklearn.model_selection import StratifiedKFold, KFold
import numpy as np
from sklearn.metrics import roc_auc_score
skf = StratifiedKFold(n_splits=5)
clf = svm.SVC(kernel='linear', C=1, random_state=100, probability=True)
auc_scores=[]
for train, test in skf.split(X_train, y_train):
    train_X = X_train.iloc[train,:]
    test_X = X_train.iloc[test]
    train_y = y_train[train]
    test_y = y_train[test]
    clf.fit(train_X, train_y)
    predict_y = clf.predict_proba(test_X)[:,1]
    auc_scores.append(roc_auc_score(test_y, predict_y))
np.array(auc_scores).mean()

0.6100000000000001

In [44]:
auc_scores

[0.6000000000000001, 0.5925, 0.5725, 0.7024999999999999, 0.5825]

In [45]:
predict_y = clf.predict_proba(X_valid)[:,1]
roc_auc_score(y_valid, predict_y)

0.6211180124223603

In [55]:
predict_z = clf.predict_proba(testing_data)[:,1]

In [56]:
aa=(predict_z>0.5).astype(int)

In [57]:
to_upload = pd.DataFrame(aa)
cc = [1000+i+1 for i in range(len(kaggle_test_aac))]
dd = pd.concat([pd.DataFrame(cc),pd.DataFrame(to_upload)],axis=1)
dd.columns = ['ID','Labels']

In [58]:
dd.to_csv('third_run.csv', index=None)

# First run

In [59]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)

In [65]:
X_train.reset_index(drop=True,inplace=True)
y_train.reset_index(drop=True,inplace=True)

In [69]:
X_train

ACAN      AGER      ALPK1    ANKRD17    APOB      APPL1      APPL2  \
0     44.1211   76.6643  1040.4443  1981.6944  0.6258  1356.1762   519.1270   
1     13.1116   24.9440   384.7138  2125.0400  0.0000  1839.7825  1204.9888   
2     45.6118   46.2410   289.7137  2054.7342  3.1456  1212.6455   833.5955   
3     16.5306   20.7384   625.7589  2485.3028  0.6011   693.9853   969.5957   
4    154.7428  103.6977   247.1865   807.4759  0.4019   702.9743   508.0386   
..        ...       ...        ...        ...     ...        ...        ...   
196  369.5060  158.6931   681.8359  1826.5266  0.3890  1767.7946   730.8440   
197  147.4978  300.7024   641.3521  1165.0571  0.4390   658.0334   699.7366   
198   26.3342   58.8318    44.2639   661.1570  0.5603   777.1397   535.0889   
199  202.5365   82.0063   101.4589  1230.8573  2.6700  1095.8329  2484.2186   
200    2.6498   46.5600   853.2223  1550.4874  3.0283   375.1301   627.6143   

         ARRB2    ASGR1    ASGR2  ...      UBE2N     UBE2V1     UBQLN1  \
0    1425.9563  33.7949  32.8561  ...  2187.9058  3674.0734  2921.6929   
1     554.8449   3.8375   2.8782  ...  2344.0998  1727.8414  3106.4918   
2     568.7323  10.3806   3.4602  ...  2074.8663  3581.3023  2382.5102   
3     756.5010  16.5306   0.9017  ...  2788.8650  3280.2029  3396.2899   
4     865.3537  30.5466   8.0386  ...  2580.3859  4031.7524  3923.2315   
..         ...      ...      ...  ...        ...        ...        ...   
196   468.6892  28.0047   3.1116  ...  3489.3038  2117.8530  3339.9455   
197   420.9833   7.0237   2.1949  ...  2223.0026  2777.0588  5190.9570   
198  1495.4475   2.8015   1.1206  ...  2274.2681  3895.2234  1603.5859   
199   527.1288  13.7313   3.8142  ...  2334.7001  2370.5235  4404.3101   
200   801.7413   5.2995  10.5990  ...  1968.0136  2558.5388  3056.3074   

          UFD1    UNC93B1  USP17L2        VCAN      WDFY1       XIAP  \
0    1793.6228  1523.5860   0.3129   5315.4971  2514.5897   921.5364   
1    1180.0352   554.8449   0.3198    469.7793  1625.8395  1488.3275   
2    1289.0783   384.0830   0.0000  13716.8921  1078.0120  2055.6779   
3    1823.1705   933.5289   0.0000    482.3934   721.9370  1613.3880   
4    2310.6873  1168.4084   0.0000   1757.2347   690.5145   945.3376   
..         ...        ...      ...         ...        ...        ...   
196  1487.3590   239.9844   0.0000    960.7157  1209.2571  1067.2890   
197  1703.6831   849.4293   0.0000   1702.3705  1396.4004  1478.9289   
198  2339.2464  2005.8832   0.0000    531.1668  1018.0698   708.7827   
199  1740.4329   807.8573   0.0000   7289.7874  1231.2387  1445.9807   
200  1362.3394  1016.3717   0.0000   1704.1734   810.0691   944.8282   

        ZCCHC3  
0     564.4997  
1     316.2776  
2     631.0160  
3     453.5400  
4     793.8103  
..         ...  
196  1055.6204  
197   590.8692  
198  1170.4721  
199   752.9322  
200   554.5566  

[201 rows x 318 columns]

In [70]:
X_test

NameError: name 'X_test' is not defined

In [68]:
print(X_train.shape)
print(X_test.shape)

(201, 318)


NameError: name 'X_test' is not defined

In [71]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train.iloc[:,:-1],X_train.iloc[:,-1])

ValueError: Unknown label type: 'continuous'

In [ ]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(df_1.iloc[:,:-1],df_1.iloc[:,-1])

In [ ]:
clf.predict(df_1.iloc[:,:-1])

In [ ]:
clf.predict(X_test.iloc[:,:-1])

In [ ]:
X_test.iloc[:,:-1]

In [ ]:
XX = pd.DataFrame(clf.predict(kaggle_test_aac.iloc[:,1:]))

In [ ]:
cc = [10000+i+1 for i in range(len(kaggle_test_aac))]

In [ ]:
dd = pd.concat([pd.DataFrame(cc),pd.DataFrame(XX)],axis=1)

In [ ]:
dd.columns = ['ID','Label']

In [ ]:
dd.to_csv('First_run.csv', index=None)

#  *Fifth run*

In [72]:
df_1 = kaggle_train_aac.iloc[:,1:]

In [73]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(df_1.,)

SyntaxError: invalid syntax (929684395.py, line 2)

In [74]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='adam', alpha=0.05, activation="logistic", learning_rate= "adaptive", max_iter=300,
                    hidden_layer_sizes=(100,30), random_state=1)
skf = StratifiedKFold(n_splits=10)
auc_scores=[]
for train, test in skf.split(X_train, y_train):
    train_X = X_train.iloc[train,:]
    test_X = X_train.iloc[test]
    train_y = y_train[train]
    test_y = y_train[test]
    clf.fit(train_X, train_y)
    predict_y = clf.predict_proba(test_X)[:,1]
    auc_scores.append(roc_auc_score(test_y, predict_y))
np.array(auc_scores).mean()

0.5263636363636363

In [75]:
predict_y = clf.predict_proba(X_valid)[:,1]
roc_auc_score(y_valid, predict_y)

0.4953416149068323

In [76]:
predict_y

array([0.61387312, 0.49030117, 0.48536167, 0.55398864, 0.32487125,
       0.54650028, 0.37381805, 0.45415802, 0.49765879, 0.39108765,
       0.40828826, 0.47525944, 0.57674518, 0.55916754, 0.52394054,
       0.54139397, 0.54269   , 0.56424479, 0.54086472, 0.46826656,
       0.55645837, 0.50145426, 0.52885142, 0.59618166, 0.47534466,
       0.56424479, 0.53924296, 0.48453084, 0.54088471, 0.5336581 ,
       0.55473708, 0.59623492, 0.53223597, 0.56857375, 0.50027498,
       0.58814544, 0.45532222, 0.4787503 , 0.40095566, 0.43811064,
       0.40662437, 0.59339112, 0.50749998, 0.53052176, 0.5275426 ,
       0.52336233, 0.54857367, 0.46857525, 0.49123396, 0.60625357,
       0.35063836])

In [77]:
df_test = kaggle_test_aac[['ID']]


In [78]:
ids=df_test['ID'].tolist()

In [79]:
aa=(predict_y>0.45).astype(int)

In [35]:
aa_list=aa.tolist()

In [36]:
df = pd.DataFrame(data = [, 
                  columns =["col1", "col2"])

SyntaxError: invalid syntax (3526099779.py, line 1)

In [37]:
df_aa=pd.DataFrame(aa)
df_aa.to_csv('Run.csv')

In [38]:
df_test['Labels'] = predict_y

ValueError: Length of values (49) does not match length of index (62)

In [ ]:
to_upload = pd.DataFrame(clf.predict_proba(testing_data)[:,1])
cc = [10000+i+1 for i in range(len(kaggle_test_aac))]
dd = pd.concat([pd.DataFrame(cc),pd.DataFrame(to_upload)],axis=1)
dd.columns = ['ID','Label']

In [ ]:
dd.to_csv('sixth_run.csv', index=None)

#   ***Fouth run

In [80]:
clf.predict(test_X)

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0])

In [81]:
clf.score(test_X, test_y)

0.4

In [82]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000)
clf = clf.fit(test_X, test_y)
skf = StratifiedKFold(n_splits=5)
auc_scores=[]
for train, test in skf.split(X_train, y_train):
    train_X = X_train.iloc[train,:]
    test_X = X_train.iloc[test]
    train_y = y_train[train]
    test_y = y_train[test]
    clf.fit(train_X, train_y)
    predict_y = clf.predict_proba(test_X)[:,1]
    auc_scores.append(roc_auc_score(test_y, predict_y))
np.array(auc_scores).mean()

0.6143214285714286

In [83]:
clf.score(test_X, test_y)

0.525

In [84]:
clf.predict(testing_data)

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0])

In [95]:
to_upload = pd.DataFrame(clf.predict_proba(testing_data)[:,1])


In [97]:
bb=(to_upload>0.5).astype(int)

In [98]:
bb

0
0    1
1    0
2    1
3    0
4    1
..  ..
99   0
100  1
101  0
102  1
103  0

[104 rows x 1 columns]

In [101]:
xx = pd.DataFrame(bb)
cc = [1000+i+1 for i in range(len(kaggle_test_aac))]
dd = pd.concat([pd.DataFrame(cc),pd.DataFrame(xx)],axis=1)
dd.columns = ['ID','Labels']

In [102]:
dd.to_csv('fifth_run.csv', index=None)

# Fifth run

In [ ]:
x